### ISSUE TITLE
unable to save a model

### ISSUE THREAD

**Issue by omerarshad** [jorgenkg/python-neural-network#9]
When you try to save trained weights, it gives error as some parameters are not initialized.

**Comment by jorgenkg** [comment]
Thanks for the heads-up, @omerarshad. This was a lagging bug since the code was refactored. I've pushed a fix.

**Comment by omerarshad** [comment]
till when it will be fixed?

**Comment by jorgenkg** [comment]
It was fixed about one hour ago. 
However, the network the previous structure of the saved file does not play nice with the new code. If you're unable to retrain the network, the solution would be to checkout this commit version instead: [b6c6b9934668f8c496c7443e48da8080294aa6b9](https://github.com/jorgenkg/python-neural-network/tree/b6c6b9934668f8c496c7443e48da8080294aa6b9)

**Comment by omerarshad** [comment]
One more question, how to use your code for multi class prediction?

**Comment by jorgenkg** [comment]
You can define how many output signals the network is supposed to have by configuring the `layers` parameter in the settings dictionary. The definition below will result in a network with a hidden layer consisting of two nodes, and a single output node. Since the network only has a single output node, the network will output a single value. 

```
settings    = {
    "layers"                : [ (2, tanh_function), (1, sigmoid_function) ],
}
network = NeuralNet( settings )
```

To make the network to return more than one value (or class, in your case), increment the number in the last tuple (eg. three output signals):

```
settings    = {
    "layers"                : [ (2, tanh_function), (3, sigmoid_function) ],
}
network = NeuralNet( settings )
```

**Comment by omerarshad** [comment]
it gives error when we declare

 (3, sigmoid_function) ],

Error : "ERROR: output size varies from the defined output setting"

**Comment by jorgenkg** [comment]
How is your dataset structured? You need to have equally many target values and output values

**Comment by omerarshad** [comment]
my data structure is given vectors of sentences and its similarity score
between 1-5 ..

e.g. [0.222,0.23,0.23] , [2.5] )

**Comment by jorgenkg** [comment]
I interpret the example you provided as the input vector has size three (`[0.222,0.23,0.23]`) and the target vector has size 1 (` [2.5]`).

You can't configure the network to have more output signals than is present in the dataset you are using when training the network. The number of output signals must be static. If some of your dataset entries has more than one output signal, you will have to preprocess them into using the same number of target values.

From the example you provided, it appears to me that the network should only have a single output.

**Comment by omerarshad** [comment]
ok i got you.. any help regarding implementing softmax on outer layer?

**Comment by jorgenkg** [comment]
I'll might look into it in the future. Until then, feel free to create a PR and create a pull request if you feel up for a calculus challenge.

**Comment by omerarshad** [comment]
ok i'll try... I liked the way you implemented NN.. How to apply linear
transformation? i want to convert 50 inputs to 5 outputs..

**Comment by jorgenkg** [comment]
Then you simply have to initialize the network as:

```python
settings    = {
    "cost_function"         : sum_squared_error,
    "n_inputs"              : 50,
    "layers"                : [ (5, linear_function) ],
}

# initialize the neural network
network = NeuralNet( settings )
```

**Comment by omerarshad** [comment]
These are my current settings where i want to implement softmax. any quick
help regarding this? because i have to implement model which uses softmax
to get probabilities.
settings = {


"cost_function" : sum_squared_error,

"n_inputs" : 200,

"layers" : [ ( 50,sigmoid_function), (5, linear_function),( 1,softmax) ],

**Comment by jorgenkg** [comment]
If you only have one output, softmax is the same as using sigmoid. So, in your case, just use sigmoid instead.

**Comment by omerarshad** [comment]
actually my output can be any number from 1-5.. so first i apply sigmoid,
then linear transformation to transform hidden layer of size 50 to 5. then
i want to apply softmax on this layer

**Comment by omerarshad** [comment]
A torch implementation of same model

:add(vecs_to_input)
:add(nn.Linear(input_dim, self.sim_nhidden))
:add(nn.Sigmoid())
:add(nn.Linear(self.sim_nhidden, self.num_classes))
:add(nn.LogSoftMax())

**Comment by jorgenkg** [comment]
I've just updated the repo. The code now features a softmax activation function. 

```python
settings = {
    "cost_function"         : softmax_cross_entropy_cost,
    "n_inputs"              : 200,       # Number of network input signals
    "layers"                : [ (50, sigmoid_function), (5, softmax_function) ]
}

# initialize the neural network
network = NeuralNet( settings )
```

This will create a network with a single hidden layer of 50 nodes and an output layer with five nodes.

**Comment by omerarshad** [comment]
hats off to you! Great job man

**Comment by omerarshad** [comment]
There is a problem when loading a saved model using softmax_cross_entropy
function.
Error is :
assert not self.cost_function == softmax_cross_entropy_cost or
self.layers[-1][1] == softmax_function,\
AttributeError: NeuralNet instance has no attribute 'cost_function'

**Comment by jorgenkg** [comment]
Fixed! :)

**Comment by omerarshad** [comment]
great work !

**Comment by omerarshad** [comment]
Hello!
I have a general question how to find delta of input layer? As my input is
output of other NN and i need to back propagate error to back to previous
NN. Any  help will be appreciated.

Thanks, Omer

**Comment by jorgenkg** [comment]
Are you sure you wish to propagate the delta out of the network, instead of training the networks separately? It sounds like you maybe overcomplicate your project. Deep neural networks are error prone, and they are therefore often (pre)trained in a greedy layerwise manner. Or in your case, network-wise manner.

Nevertheless, if you add the function below to the `NeuralNet.class`, the code will generate the deltas for the input layer. 

```python
def first_layer_deltas(self, trainingset ):
        training_data              = np.array( [instance.features for instance in trainingset ] )
        training_targets           = np.array( [instance.targets  for instance in trainingset ] )
        
        layer_indexes              = range( len(self.layers) )[::-1]    # reversed
        input_signals, derivatives = self.update( training_data, trace=True )
        
        out                        = input_signals[-1]
        cost_derivative            = self.cost_function(out, training_targets, derivative=True).T
        delta                      = cost_derivative * derivatives[-1]
        
        for i in layer_indexes:
            # Loop over the weight layers in reversed order to calculate the deltas
            
            # Skip the bias weight
            weight_delta = np.dot( self.weights[ i ][1:,:], delta )
            
            # Calculate the delta for the subsequent layer
            delta = weight_delta * (1 if i == 0 else derivatives[i-1])
        #end weight adjustment loop
        
        return delta
#end
```

Note: I haven't tested this code

**Comment by omerarshad** [comment]
Yes i have no other option than this. My unsupervised training is based on
supervised training. So I have to add delta of supervised part to
unsupervised part.

**Comment by omerarshad** [comment]
Hello! What can be the problem if my error is not decreasing? it is stuck
to some point and not decreasing anymore. I am using softmax cross entropy
as cost function.

**Comment by jorgenkg** [comment]
The standard tricks are::

- preprocessing
- trying different activation functions (in the lower layers)
   - tried `tanh`?
- try different learning functions

There are not bulletproof strategies - it might just be that your dataset is very difficult to learn.

**Comment by omerarshad** [comment]
I am optimizing weights of two networks using "L-bfgs". One network is
doing well but the network i build using your code is stuck at error 1.5.
This is howi get gradient and error. Weights are assigned after receiving
from lbfgs

grad_sup +=
network.gradient(theta_supervised,training_data,training_targets)

sup_error += network.error(theta_supervised,training_data,training_targets)

**Comment by jorgenkg** [comment]
What is the `theta_supervised` term? The functions `network.gradient()` and `network.error()` takes `weight_vector` (a list of floats of size `network.n_weights`) as the first argument, in addition to the latter two which you've correctly specified.

Using the latest revision of the repo:

```python
# Train the network using SciPy
from learning_algorithms import scipyoptimize
scipyoptimize(
        network,
        your_dataset,    # change this to your dataset
        method               = "L-BFGS-B",
        ERROR_LIMIT          = 1e-4,
    )
```

This snippet will successfully train the network using SciPy's *Limited-memory BFGS* implementation through `scipy.optimize.minimize`.

**Comment by omerarshad** [comment]
WE are training two networks, so we pass concatenated array of weights to
"L-BFGS",
theta_supervised are the weights of one network which we got after one
iteration of LBFGS

main weight vector contains weights of two networks

**Comment by jorgenkg** [comment]
I've never tried anything similar, so unfortunately I haven't got any suggestions.
Do you get the weight vector of the network by calling `get_weights()`?

**Comment by omerarshad** [comment]
There is some problem . Is softmax cost function implemented correctly?
there might be come error as i am unable to find why always my NN stuck at
error 1.56

**Comment by jorgenkg** [comment]
I believe you're onto something. I'll take a close look in the weekend, I haven't got too much spare time during the workweek.

**Comment by jorgenkg** [comment]
No, the softmax derivative appears to be correctly calculated. I'm struggling to understand why the network won't learn your dataset. Are you able to share your dataset? Have you tried to use `tanh` on the intermediate layers of the network?

**Comment by omerarshad** [comment]
i have a RAE, it outputs sentence vectors, these sentence vectors are given
as input to next NN which uses Softmax layer to calculate to which class
the sentence belongs.

Problem: the second network is created using your code, and it's error
never decreases from 1.5, so dataset to supervised NN is output of
unsupervised NN which produces sentence vectors.

**Comment by jorgenkg** [comment]
Is my network the last network in the chain of networks?

**Comment by omerarshad** [comment]
yes

**Comment by jorgenkg** [comment]
May you please try again with the code I pushed to the repo? I've just merged the master branch with `dev`. This introduced a lot of improvements, specifically on the numerical stability of calculating derivatives for `softmax`.

**Comment by omerarshad** [comment]
ok i'll

**Comment by omerarshad** [comment]
what if i just copy cost and activation function?

**Comment by jorgenkg** [comment]
From the top of my head, I believe that might work - no guarantees though 😊

**Comment by omerarshad** [comment]
i have changed cost function and activation function.. let's see if any
miracle happens :)

**Comment by omerarshad** [comment]
softmax_cross_entropy_cost is changed to "softmax_neg_loss"?

**Comment by jorgenkg** [comment]
Yes, that's right. In addition to changing the name, the calculation has changed from:

`np.mean(-np.sum(targets * np.log( outputs ), axis=1))`

to 

`-np.sum(targets * np.log( outputs ))`

The update (removing np.mean) is intertwined with the calculation of the gradients. Therefore, if you're trying to update the code simply by copy-pasting the cost and activation function, you will most likely be better off using `np.mean(-np.sum(targets * np.log( outputs ), axis=1))`.

**Comment by omerarshad** [comment]
So you prefer that i use the old cost function?

**Comment by jorgenkg** [comment]
Yes, I believe you should stick to the old version.

**Comment by omerarshad** [comment]
but if i can get good results then i can change the whole code even. Will
it really ?

**Comment by jorgenkg** [comment]
The only way I can guarantee that the calculations are correct, will be if the code is updated with the new files. 

I'm hoping everything works out for you!

**Comment by omerarshad** [comment]
Yes i am ready to change all files, hoping that it will work better than
before

**Comment by omerarshad** [comment]
You wrote a first_layer_deltas code? did u removed that?

**Comment by jorgenkg** [comment]
No, I never added it to the code base. I just posted a snippet for you in this chat. This code calculates the same result, updated to the newest version. Just add the method to the NeuralNet class.

```python
def first_layer_delta(self, trainingset, cost_function ):
    assert softmax_function != self.layers[-1][1] or cost_function == softmax_neg_loss,\
        "When using the `softmax` activation function, the cost function MUST be `softmax_neg_loss`."
    assert cost_function != softmax_neg_loss or softmax_function == self.layers[-1][1],\
        "When using the `softmax_neg_loss` cost function, the activation function in the final layer MUST be `softmax`."
    
    training_data           = np.array( [instance.features for instance in trainingset ] )
    training_targets        = np.array( [instance.targets  for instance in trainingset ] )
    
    input_signals, derivatives  = self.update( training_data, trace=True )                  
    out                         = input_signals[-1]
    cost_derivative             = cost_function(out, training_targets, derivative=True).T
    delta                       = cost_derivative * derivatives[-1]
    
    layer_indexes               = range( len(self.layers) )[::-1]    # reversed
    
    for i in layer_indexes:
        # i!= 0 because we don't want calculate the delta unnecessarily.
        weight_delta        = np.dot( self.weights[ i ][1:,:], delta ) # Skip the bias weight

        # Calculate the delta for the subsequent layer
        delta               = weight_delta * (1 if i == 0 else derivatives[i-1])
    #end weight adjustment loop
    
    return delta
# end gradient
```

How to:

```python
dataset             = [ Instance( [0,0], [0] ), Instance( [1,0], [1] ), Instance( [0,1], [1] ), Instance( [1,1], [0] ) ]
network.first_layer_delta( dataset, cost_function ) # return the deltas
```

**Comment by omerarshad** [comment]
Hi!

I have a question regarding scipy optimizer, for 10 iterations it calls
function to be optimized many times.. what does this mean? and why it calls
function more than 10 times?

**Comment by jorgenkg** [comment]
I'm iterpreting from you question that it is `minimize()` that calls the function repeatedly?

I've never worked with the SciPy code base, and I have unfortunately no idea how it operates.

**Comment by omerarshad** [comment]
yes exactly, that minimize() keeps on calling the objective function many
times.

**Comment by jorgenkg** [comment]
Maybe StackOverflow can help you out?

**Comment by omerarshad** [comment]
I am implementing SGD, where i need to declare a mini batch, but if i use
scipy i can't control no. of epocs. anyways thanks a lot for your help :)

**Comment by omerarshad** [comment]
Hi agai !
if i call network.get_Weights and network.gradient, does this mean that i
get following arrays
weight [...]
gradient[...] which means that gradient[i] corresponds to weight[i]? and i
can update weights manually using the respective gradient?

**Comment by omerarshad** [comment]
Getting this error in conjugate gradient method

"nn/learning_algorithms.py:317: RuntimeWarning: invalid value encountered
in double_scalars
  comparison      = 2 * delta * (f_old - f_new)/np.power( phi, 2 )"

**Comment by omerarshad** [comment]
How to use your back-propogation as a SGD?

**Comment by jorgenkg** [comment]
Hello @omerarshad! 

I'm sorry for taking so long to respond lately, but I'm down to my last four weeks writing my thesis.

SGD is implemented in the `dev` branch :)

**Comment by omerarshad** [comment]
So i can trust it? And best of luck for your thesis :)

**Comment by jorgenkg** [comment]
Hey, thanks :)
Just drop me a message if something breaks!

**Comment by omerarshad** [comment]
Hi!

When i call network.gradient() method, it returns first order derivative,
what changes i need to make so that it returns 2nd order derivative?

Thanks, Omer

**Comment by jorgenkg** [comment]
I'm not sure. I've never worked with second order (hessian) learning i neural networks. I think the hessian is often approximated, rather than analytically calculated.

**Comment by omerarshad** [comment]
So is it possible to convert gradient provided by your network to hessian
matrix?

**Comment by jorgenkg** [comment]
The code returns the Jacobian (first order derivatives). However, [this paper by Yu and Wilamowski](http://www.eng.auburn.edu/~wilambm/pap/2011/Neural%20Network%20Training%20with%20Second%20Order%20Algorithms.PDF)  seem to approximate the Hessian using the first order derivatives. You might have som luck reading their work.

> Yu, H., and B. M. Wilamowski. "Neural network training with second order algorithms." Human–Computer Systems Interaction: Backgrounds and Applications 2. Springer Berlin Heidelberg, 2012. 463-476.

**Comment by omerarshad** [comment]
Hi jorgen! I hope you are doing good in your thesis, How to calculate
gradient for input layer in your code?

Omer.

**Comment by jorgenkg** [comment]
Thanks, the thesis was just submitted!

The code for calculating the deltas has been posted a few times over in this comment thread, however it required a slight modification:

```python
def network_deltas( network, trainingset, cost_function ):
    import numpy as np
    training_data              = np.array( [instance.features for instance in trainingset ] )
    training_targets           = np.array( [instance.targets  for instance in trainingset ] )
    layer_indexes              = range( len(network.layers) )[::-1]    # reversed
    
    input_signals, derivatives = network.update( training_data, trace=True )
    out                        = input_signals[-1]
    cost_derivative            = cost_function(out, training_targets, derivative=True).T
    delta                      = cost_derivative * derivatives[-1]
    
    deltas                     = [ delta ]
    for i in layer_indexes:
        delta = np.dot( network.weights[ i ][1:,:], delta ) * (1 if i == 0 else derivatives[i-1])
        deltas.append( delta )
    #end
            
    return deltas[::-1] # the deltas of [ layer1, layer2, .., layerN ]
#end

# return a list of the gradients of each layer
print network_deltas( network, training_data, cost_function )
```

**Comment by omerarshad** [comment]
Hey!

I  hope you will be doing good. How to cite your implementation in my
thesis? as i am done with experiments and now want to cite your work in my
thesis document.

Thanks, Omer

**Comment by jorgenkg** [comment]
Hello again,

Congratulations! I personally feel no need for you to cite my work, but if you're interested in extending your reference list, you should cite it as a webpage directed at the project website.

Best regards

**Comment by omerarshad** [comment]
hello! Do u plan to implement adaptive learning rate technique?

**Comment by jorgenkg** [comment]
Hi,

It's implemented (but not documented) in the 'dev' branch. Take a look at the file named example.py in the top directory:)

I'm in the process of thoroughly writing documentation for readthedocs, but I'm not done yet. 

The various algorithms are listed in:
learning_algorithms/back propagation/variations

**Comment by omerarshad** [comment]
can you demonstrate how to use adam? Because there is no documentation for
it. I'll be very thankful to you

**Comment by jorgenkg** [comment]
```python
from nimblenet.activation_functions import sigmoid_function
from nimblenet.cost_functions import cross_entropy_cost
from nimblenet.learning_algorithms import *
from nimblenet.neuralnet import NeuralNet
from nimblenet.data_structures import Instance
from nimblenet.tools import print_test


training_data = test_data = [ Instance( [0,0], [0] ), Instance( [1,0], [1] ), Instance( [0,1], [1] ), Instance( [1,1], [1] ) ]
cost_function       = cross_entropy_cost
settings            = {
    "n_inputs"              : 2,       # Number of network input signals
    "layers"                : [  (3, sigmoid_function), (1, sigmoid_function) ],
}

# initialize the neural network
network             = NeuralNet( settings )

# Train the network using backpropagation
Adam(
        network,                            # the network to train
        training_data,                      # specify the training set
        test_data,                          # specify the test set
        cost_function,                      # specify the cost function to calculate error
        
        ERROR_LIMIT             = 1e-2,     # define an acceptable error limit 
        #max_iterations         = 100,      # continues until the error limit is reach if this argument is skipped
                                
        batch_size              = 0,        # 1 := no batch learning, 0 := entire trainingset as a batch, anything else := batch size
        print_rate              = 1000,     # print error status every `print_rate` epoch.
        save_trained_network    = False,     # Whether to write the trained weights to disk

        # Adam specific parameters
        beta1 = 0.9, beta2 = 0.999, epsilon = 1e-8
    )


# Print a network test
print_test( network, training_data, cost_function )
```

**Comment by jorgenkg** [comment]
I've just published a more [complete documentation for the code on Read the Docs](http://nimblenet.readthedocs.io), if the code example didn't help you out.
